# level.py - Level loading and management
import pygame

# Define 10 different maze layouts
LEVEL_LAYOUTS = [
    # Level 1 - Simple classic layout
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W............WW............W",
        "W.WWWW.WWWWW.WW.WWWWW.WWWW.W",
        "WoWWWW.WWWWW.WW.WWWWW.WWWWoW",
        "W.WWWW.WWWWW.WW.WWWWW.WWWW.W",
        "W..........................W",
        "W.WWWW.WW.WWWWWWWW.WW.WWWW.W",
        "W.WWWW.WW.WWWWWWWW.WW.WWWW.W",
        "W......WW....WW....WW......W",
        "WWWWWW.WWWWW WW WWWWW.WWWWWW",
        "WWWWWW.WWWWW WW WWWWW.WWWWWW",
        "WWWWWW.WW          WW.WWWWWW",
        "WWWWWW.WW WWWGGWWW WW.WWWWWW",
        "WWWWWW.WW W      W WW.WWWWWW",
        "      .   W      W   .      ",
        "WWWWWW.WW W      W WW.WWWWWW",
        "WWWWWW.WW WWWWWWWW WW.WWWWWW",
        "WWWWWW.WW          WW.WWWWWW",
        "WWWWWW.WW WWWWWWWW WW.WWWWWW",
        "WWWWWW.WW WWWWWWWW WW.WWWWWW",
        "W............WW............W",
        "W.WWWW.WWWWW.WW.WWWWW.WWWW.W",
        "W.WWWW.WWWWW.WW.WWWWW.WWWW.W",
        "Wo..WW................WW..oW",
        "WWW.WW.WW.WWWWWWWW.WW.WW.WWW",
        "WWW.WW.WW.WWWWWWWW.WW.WW.WWW",
        "W......WW....WW....WW......W",
        "W.WWWWWWWWWW.WW.WWWWWWWWWW.W",
        "W.WWWWWWWWWW.WW.WWWWWWWWWW.W",
        "W...........P............W.W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 2 - More complex layout
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W.........................oW",
        "W.WWWWWW.WWWWW.WWWWW.WWWWW.W",
        "W.WWWWWW.WWWWW.WWWWW.WWWWW.W",
        "W.WW.....WW....WW....WW....W",
        "W.WW.WWW.WW.WWWWW.WWWWW.WW.W",
        "W.WW.WWW.WW.WWWWW.WWWWW.WW.W",
        "W....WWW.............WWW...W",
        "WWWW.WWW.WWW.WWW.WWW.WWW.WWW",
        "WWWW.WWW.WWW.WWW.WWW.WWW.WWW",
        "W....WWW.WWW.....WWW.WWW...W",
        "W.WWWWWW.WWWWW.WWWWW.WWWWW.W",
        "W.WWWWWW.WWWWW.WWWWW.WWWWW.W",
        "Wo........G...P...G.......oW",
        "WWWWWWWW.WWWWW.WWWWW.WWWWWWW",
        "WWWWWWWW.WWWWW.WWWWW.WWWWWWW",
        "W.............W............W",
        "W.WWW.WWWWWWW.W.WWWWWWW.WWW.",
        "W.WWW.WWWWWWW.W.WWWWWWW.WWW.",
        "W.WWW.........W.........WWW.",
        "W.WWW.WWWWWWWWWWWWWWWWW.WWW.",
        "W.WWW.WWWWWWWWWWWWWWWWW.WWW.",
        "W.....WWWWWWWWWWWWWWWWW.....",
        "WWWWW.WWWWWWWWWWWWWWWWW.WWWW",
        "WWWWW.WWWWWWWWWWWWWWWWW.WWWW",
        "WWWWW...................WWWW",
        "WWWWWoWWWWWWWWWWWWWWWWWoWWWW",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 3 - Spiral maze
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W..........................W",
        "W.WWWWWWWWWWWWWWWWWWWWWWWW.W",
        "W.WP.......................W",
        "W.W.WWWWWWWWWWWWWWWWWWWWW.W",
        "W.W.W.....................W",
        "W.W.W.WWWWWWWWWWWWWWWWWW.W.W",
        "W.W.W.W...................W",
        "W.W.W.W.WWWWWWWWWWWWWWWW.W.W",
        "W.W.W.W.W.................W",
        "W.W.W.W.W.WWWWWWWWWWWWWW.W.W",
        "W.W.W.W.W.W...............W",
        "W.W.W.W.W.W.WWWWWWWWWWWW.W.W",
        "W.W.W.W.W.W.W....G.......W.W",
        "W.W.W.W.W.W.W.WWWWWWWWWW.W.W",
        "WGW.W.W.W.W.W.W.........W.W",
        "W...W.W.W.W.W.W.WWWWWWW.W.W",
        "WWW.W.W.W.W.W.W.W.....W.W.W",
        "W...W.W.W.W.W.W.WGW.W.W.W.W",
        "W.WWW.W.W.W.W.W...W.W.W.W.W",
        "W.....W.W.W.W.WWW.W.W.W.W.W",
        "WWWWWWW.W.W.W...W.W.W.W.W.W",
        "W.......W.W.WWW.W.W.W.W.W.W",
        "W.WWWWWWW.W...W.W.W.W.W.W.W",
        "W.........WWW.W.W.W.W.W...W",
        "WWWWWWWWWW....W.W.W.W.WWW.W",
        "Wo............W.W.W.W.....W",
        "WWWWWWWWWWWWWWW.W.W.WWWWWWW",
        "Wo..............W.........oW",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 4 - Open center
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W..........................W",
        "W.WWWW.WWWWW.WWWW.WWWWW.WW.W",
        "WoWWWW.WWWWW.WWWW.WWWWW.WWoW",
        "W.WWWW...WWW.WWWW.WWW...WW.W",
        "W......W....WWWWWW....W....W",
        "WWWWWW.WWWW........WWWW.WWWW",
        "WWWWWW.WWWWW.WWWW.WWWWW.WWWW",
        "WWWWWW.WWWWW.WWWW.WWWWW.WWWW",
        "WWWWWW.WW.............WW.WWWW",
        "WWWWWW.WW.WWWWWWWWWW.WW.WWWW",
        "WWWWWW.WW.WWWWWWWWWW.WW.WWWW",
        "WWWWWW.WW.WW      WW.WW.WWWW",
        "      .   WW      WW   .    ",
        "WWWWWW.WW WW  GG  WW WW.WWWW",
        "WWWWWW.WW WW  GG  WW WW.WWWW",
        "WWWWWW.WW WW      WW WW.WWWW",
        "WWWWWW.WW WWWWWWWWWW WW.WWWW",
        "WWWWWW.WW          P WW.WWWW",
        "WWWWWW.WW WWWWWWWWWWWWW.WWWW",
        "WWWWWW.WW WWWWWWWWWWWWW.WWWW",
        "W......WW.............WW...W",
        "W.WWWW.WWWWW.WWWW.WWWWW.WW.W",
        "W.WWWW.WWWWW.WWWW.WWWWW.WW.W",
        "Wo.WWW...........WWW...WWoW",
        "WWW.WWWWWWWWWWWWWWWWWWW.WWWW",
        "WWW..........................W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 5 - Checkerboard
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.........................oW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "Wo........................W",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W...G.....................oW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W...P.....G................W",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W.........................oW",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "Wo.........................W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 6 - Pathways
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W..........................W",
        "W.WWWWWWWWWWWWWWWWWWWWWWWW.W",
        "W.W........................W",
        "W.W.WWWWWWWWWWWWWWWWWWWWWW.W",
        "W.W.W......................W",
        "W.W.W.WWWWWWWWWWWWWWWWWWWW.W",
        "W.W.W.W....................W",
        "W.W.W.W.WWWWWWWWWWWWWWWWWW.W",
        "W.W.W.W.W................W.W",
        "W.W.W.W.W.WWWWWWWWWWWWWW.W.W",
        "W.W.W.W.W.W...g..........W.W",
        "W.W.W.W.W.W.WWWWWW.WWWWW.W.W",
        "W.W.W.W.W.W.WP........GW.W.W",
        "W.W.W.W.W.W.WWW.WWWWWWWW.W.W",
        "W.W.W.W.W.W..............W.W",
        "W.W.W.W.W.WWWWWWWWWWWWWW.W.W",
        "W.W.W.W.W................W.W",
        "W.W.W.W.WWWWWWWWWWWWWWWW.W.W",
        "W.W.W.W..................W.W",
        "W.W.W.WWWWWWWWWWWWWWWWWW.W.W",
        "W.W.W.....................W.W",
        "W.W.WWWWWWWWWWWWWWWWWWWW.W.W",
        "W.W.......................W.W",
        "W.WWWWWWWWWWWWWWWWWWWWWW.W.W",
        "W.........................W.W",
        "WoWWWWWWWWWWWWWWWWWWWWWWWWoW",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 7 - Chambers
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W...........W............W.W",
        "W.WWWWWWWWW.W.WWWWWWWWWW.W.W",
        "W.W.......W.W.W........W.W.W",
        "W.W.WWWWW.W.W.W.WWWWWW.W.W.W",
        "W.W.W...W.W.W.W.W....W.W.W.W",
        "W.W.W.W.W.W.W.W.W.WW.W.W.W.W",
        "W.W.W.W.W.W.W.W.W.WW.W.W.W.W",
        "W...W.W.W...W...W.WW.W...W.W",
        "WWWWW.W.WWWWWWWWW.WW.WWWWW.W",
        "Wo....W...........WW.....oW",
        "WWWWWWWWWWWWWWWWW.WWWWWWWWWW",
        "W.............W...W........W",
        "W.WWWWWWWWWWW.W.WWW.WWWWWW.W",
        "W.W...........W...W.W....W.W",
        "W.W.WWWWWWWWWWWWW.W.W.WW.W.W",
        "W.W.W.............W.W.WW.W.W",
        "W.W.W.WWWWWWWWWWWWW.W.WW.W.W",
        "W.W.W.W...........GW.WW.W.W",
        "W.W.W.W.WWWWWWWWWWW..WW.W.W",
        "W.W.W.W.WP..G........WW.W.W",
        "W.W.W.W.WWWWWWWWWWWWWWW.W.W",
        "W.W.W.W...............W.W.W",
        "W.W.W.WWWWWWWWWWWWWWW.W.W.W",
        "W.W.W.................W.W.W",
        "W.W.WWWWWWWWWWWWWWWWWWW.W.W",
        "W.W.......................W",
        "WoWWWWWWWWWWWWWWWWWWWWWWWWoW",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 8 - Scattered Walls
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W.................G........W",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "W..........................W",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "W..........................W",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "W.......................W..W",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "WP.........................W",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "W..........................W",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "W...G.....................W",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "WWW.WWWWW.WWWWW.WWWWW.WWW.WW",
        "W.........................oW",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "W.WWWW.WWWWW.WWWWW.WWWW.WW.W",
        "Wo.........................W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 9 - Zigzag
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.........................oW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "Wo........................W",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W...G.....................oW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W...P.....G................W",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W.........................oW",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "Wo.........................W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ],
    
    # Level 10 - Final Challenge
    [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.........................oW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "Wo........................W",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W...G.....................oW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W..........................W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W...P.....G................W",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "WWWW.WWWW.WWWW.WWWW.WWWW.WWW",
        "W.........................oW",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "W.WWWW.WWWW.WWWW.WWWW.WWWW.W",
        "Wo.........................W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]
]

def load_level(level_num):
    if 1 <= level_num <= len(LEVEL_LAYOUTS):
        map_data = LEVEL_LAYOUTS[level_num - 1]
        wall_rects = []
        
        # Create wall rectangles based on the map data
        for y, row in enumerate(map_data):
            for x, cell in enumerate(row):
                if cell == 'W':
                    # Create wall rectangle with proper grid alignment and width 15
                    wall_rect = pygame.Rect(
                        x * 20,  # x position
                        y * 20,  # y position
                        15,      # width of 15
                        15       # height of 15
                    )
                    # Center the wall rectangle
                    wall_rect.x += 2.5  # Shift right by 2.5 pixels
                    wall_rect.y += 2.5  # Shift down by 2.5 pixels
                    wall_rects.append(wall_rect)
        
        return map_data, wall_rects
    else:
        # Return a default level if the level number is invalid
        return LEVEL_LAYOUTS[0], []